model:
    arch: icnetNonBN
data:
    dataset: cityscapes
    version: cityscapes
    img_norm: False
    train_split: train
    val_split: val
    img_rows: 1025
    img_cols: 2049
    path: /workspace/data/cityscapes/
training:
    train_iters: 9999000
    batch_size: 1
    n_workers: 10
    val_interval: 12000
    print_interval: 12000
    optimizer:
        name: adam
        lr: 0.001
    l_rate: 0.001
    augmentations:
        saturation: 0.25
        hue: 0.05
        contrast: 0.125
        vflip: 0.5
    lr_schedule: 
        name: poly_lr
        max_iter: 12000
        
    momentum: 0.9
    weight_decay: 0.0001
    resume: /workspace/data/bestmodel/icnetNonBN_csmap_iou64.pkl
    reset_epoch: 1
    visdom: False
    loss:
        name: multi_scale_cross_entropy
        size_average: False
        try_downsampling: True
