model:
    arch: icnetBN
data:
    dataset: cityscapes
    version: pascal
    img_norm: False
    train_split: train
    val_split: val
    img_rows: 1024
    img_cols: 1820
    path: /workspace/data/cityscapes/
training:
    train_iters: 7500
    batch_size: 4
    n_workers: 1
    val_interval: 744
    print_interval: 744
    optimizer:
        name: adam
        lr: 5.0e-5
        weight_decay: 0.0005
    augmentations:
        rcrop: [1024, 1820]
        saturation: 0.25
        hue: 0.05
        contrast: 0.125
        vflip: 0.5

    l_rate: 5.0e-5
    lr_schedule: 
        name: cosine_annealing
        T_max: 500
    momentum: 0.99
    weight_decay: 0.0005
    resume: /workspace/data/bestmodel/icnetbn_cs_iou50.pkl
    visdom: False
    loss:
        name: multi_scale_cross_entropy
        size_average: False
