model:
    arch: icnetNonBN
    input_size: [1080, 1920]
data:
    dataset: vistas
    version: vistas
    img_norm: True
    train_split: training
    val_split: validation
    path: /workspace/data/mapillary/
    root: /workspace/data/mapillary/
    val_asp_ratio_delta: 1.5
validation:
    boost_retries: 8
    augmentations:
        rcrop: [1080, 1920]
training:
    boost_indices: [[22, 22, 56, 56, 56, 56, 56, 1, 1, 1, 1, 18, 56, 56, 56, 56, 0, 22, 34, 37, 56, 8, 9, 10, 1, 53], [34, 34, 60, 62, 43, 32, 56, 1, 18, 22, 26, 60, 43, 42, 32, 22, 56, 34, 53], [40, 42, 56, 56, 56, 1, 1, 26, 26,  42, 42, 22, 22, 40, 60, 53, 18, 0, 56, 56, 56, 56, 56, 1, 1, 26, 26,  42, 42, 22, 22, 40, 60, 0, 58, 53], [37, 37, 38, 8, 53, 56, 1, 18, 22, 26, 43, 37, 37, 38, 8, 56, 1, 18], [40, 42, 56, 56, 56, 1, 1, 26, 26, 42, 42, 22, 22, 40, 60, 18, 0,56, 56, 56, 56, 1, 1, 26, 26, 42, 42, 22, 22, 40, 60, 18, 0], -1]
    boost_max_ratio: 0.9
    boost_retries: 8
    resume: /workspace/data/bestmodel/icnetNonBN_vis_iou24p1.pkl
    train_iters: 9999000
    batch_size: 5
    n_workers: 10
    val_interval: 4500
    print_interval: 4500
    optimizer:
        name: sgd
        lr: 5.0e-4
        weight_decay: 0.0001
        momentum: 0.9
    l_rate: 0.0001
    augmentations:
        rsize: [1920, 7680]
        rcrop: [1080, 1920]
        rotate: 8
        saturation: 0.25
        hue: 0.08
        contrast: 0.125
        vflip: 0.5
    lr_schedule: 
        name: poly_lr
        max_iter: 14100
    momentum: 0.9
    weight_decay: 0.0001
    reset_epoch: 1
    reset_optimizer: True
    visdom: False
    loss:
        name: multi_scale_cross_entropy
        size_average: True
        try_downsampling: True
