model:
    arch: icnetNonBN
data:
    dataset: vistas
    version: cityscapes
    img_norm: False
    train_split: train
    val_split: val
    img_rows: 1025
    img_cols: 2049
    path: /workspace/data/mapillary
training:
    train_iters: 7500
    batch_size: 1
    n_workers: 1
    val_interval: 3000
    print_interval: 3000
    optimizer:
        name: adam
        lr: 1.0e-4
    l_rate: 1.0e-4
    augmentations:
        saturation: 0.25
        hue: 0.05
        contrast: 0.125
        vflip: 0.5
    lr_schedule: 
        name: cosine_annealing
        T_max: 500
    momentum: 0.99
    weight_decay: 0.0005
    resume: /workspace/data/bestmodel/icnet_cityscapes_trainval_90k.pth
    visdom: False
    loss:
        name: cross_entropy
        size_average: False
